"on":
  push:
    branches:
    - master
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Deploy stack
      timeout-minutes: 30
      uses: porter-dev/porter-cli-action@dev
      with:
        command: apply -f porter.yaml
      env:
        PORTER_CLUSTER: "1"
        PORTER_HOST: https://23f1-2600-4041-5000-8c00-355a-fdd-f0b4-4c02.ngrok-free.app
        PORTER_PROJECT: "1"
        PORTER_STACK_NAME: stackevent
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_1_1 }}
